version: '3.4'

services:
  publisherapplication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  workerprocess:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
